#Tells Docker to use this Node version
FROM node:12.16.3

#Tells Docker to create folder called code inside Docker image
WORKDIR /code

#Environemnt variables can be accessed inside image
ENV  PORT 80

#Copies the package.json file into code folder
COPY package.json /code/package.json

#Runs node package manager and install dependencies
RUN npm install

#Copies all code from current working directory into code directory in image
COPY . /code




# First step
# npm init -y


# To build the docker file
# docker build -t my-node-app .

# To build the docker file
# docker run -p 8000:80 my-node-app 

 ass 3 -https://1drv.ms/b/c/A86C589506A70137/EUGqnkShZmZPlvlum1BtUfwBQbSb6EpE8PHpwCRxu-84yQ

https://1drv.ms/b/c/A86C589506A70137/EVsoREuIw2hJpfzueZgRQZEBhHenNRoVbrG3KLsfPHLN0Q

https://1drv.ms/b/c/A86C589506A70137/EaOnCuHXOUJBsNT8Id8VV7gBNzm5rbhNI6vDFe0mDEf0yQ

https://1drv.ms/b/c/A86C589506A70137/EYOtK52ncvtInbkQhzS-BmMBKfPg2G91X6J9JG_mvhAb4A

https://1drv.ms/b/c/A86C589506A70137/EcQvE5NfQh9EhghPUqlbi24B08FjjwDCsr_aIMcUotOpHg

https://1drv.ms/b/c/A86C589506A70137/EShXa6Mek_lModdEJYauRU0BD-GwzdCi1WmKxZt2mwGPpw




